### ISSUE TITLE
Some link message dont have description attributes

### ISSUE THREAD

**Issue by xufan6** [blueset/ehForwarderBot#10]
```
2017-01-15 21:28:37,991: plugins.eh_wechat_slave.WeChatChannel [INFO]
    ---
New Link msg, {'MediaId': '', 'CreateTime': 1484515715, 'Ticket': '', 'Content': '<msg> <appmsg appid="" sdkver="0"> \t<title><![CDATA[账户查询]]></title> \t<des><![CDATA[ ]]></des> \t<action></action> \t<type>5</type> \t<showtype>1</showtype>     <soundtype>0</soundtype> \t<content><![CDATA[]]></content> \t<contentattr>0</contentattr> \t<url><![CDATA[https://open.weixin.qq.com/connect/oauth2/authorize?appid=wxe9dxxx&redirect_uri=https://weixin.spdbccc.com.cn/spdbcccWeChatPage/linkRedirection.do?activityKey%3Dd&response_type=code&scope=snsapi_base&state=STATE#wechat_redirect]]></url> \t<lowurl><![CDATA[]]></lowurl> \t<appattach> \t\t<totallen>0</totallen> \t\t<attachid></attachid> \t\t<fileext></fileext> \t</appattach> \t<extinfo></extinfo> \t<mmreader> \t\t<category type="0" count="1"> \t\t\t<name><![CDATA[浦发银行信用卡]]></name> \t\t\t<topnew> \t\t\t\t<cover><![CDATA[http://weixin.spdbccc.com.cn/spdbcccfile/file/image/ImageText/zhanghuchaxun_201610271715.jpg]]></cover> \t\t\t\t<width>336</width> \t\t\t\t<height>215</height> \t\t\t\t<digest><![CDATA[ ]]></digest> \t\t\t</topnew> \t\t\t\t<item> \t<itemshowtype>0</itemshowtype> \t<title><![CDATA[账户查询]]></title> \t<url><![CDATA[https://open.weixin.qq.com/connect/oauth2/authorize?appid=wxe9dxxx&redirect_uri=https://weixin.spdbccc.com.cn/spdbcccWeChatPage/linkRedirection.do?activityKey%3Dd&response_type=code&scope=snsapi_base&state=STATE#wechat_redirect]]></url> \t<shorturl><![CDATA[]]></shorturl> \t<longurl><![CDATA[]]></longurl> \t<pub_time>1484515715</pub_time> \t<cover><![CDATA[http://weixin.spdbccc.com.cn/spdbcccfile/file/image/ImageText/zhanghuchaxun_201610271715.jpg]]></cover> \t<tweetid></tweetid> \t<digest><![CDATA[ ]]></digest> \t<fileid>0</fileid> \t<sources> \t<source> \t<name><![CDATA[浦发银行信用卡]]></name> \t</source> \t</sources> \t<styles></styles>\t<native_url></native_url>    <del_flag>0</del_flag>     <contentattr>0</contentattr>     <play_length>0</play_length> \t<play_url></play_url> \t<player><![CDATA[]]></player> \t</item> \t\t</category> \t\t<publisher> \t\t\t<username><![CDATA[gh_4e]]></username> \t\t\t<nickname><![CDATA[浦发银行信用卡]]></nickname> \t\t</publisher> \t\t<template_header></template_header> \t\t<template_detail></template_detail> \t    <forbid_forward>0</forbid_forward> \t</mmreader> \t<thumburl><![CDATA[http://weixin.spdbccc.com.cn/spdbcccfile/file/image/ImageText/zhanghuchaxun_201610271715.jpg]]></thumburl> \t                          </appmsg><fromusername><![CDATA[gh_4e]]></fromusername><appinfo><version>0</version><appname><![CDATA[浦发银行信用卡]]></appname><isforceupdate>1</isforceupdate></appinfo></msg>', 'FromUserName': '@42abcde', 'Url': 'https://open.weixin.qq.com/connect/oauth2/authorize?appid=wxe9d&amp;redirect_uri=https://weixin.spdbccc.com.cn/spdbcccWeChatPage/linkRedirection.do?activityKey%3Dczd&amp;response_type=code&amp;scope=snsapi_base&amp;state=STATE#wechat_redirect', 'OriContent': '', 'FileName': '账户查询', 'MsgType': 49, 'ImgWidth': 0, 'Type': 'Sharing', 'Status': 3, 'ImgStatus': 1, 'Text': '账户查询', 'StatusNotifyUserName': '', 'MsgId': '269', 'PlayLength': 0, 'AppInfo': {'AppID': '', 'Type': 0}, 'NewMsgId': 269, 'VoiceLength': 0, 'ToUserName': '@c2b', 'FileSize': '0', 'ImgHeight': 0, 'AppMsgType': 5, 'StatusNotifyCode': 0, 'RecommendInfo': {'NickName': '', 'QQNum': 0, 'Content': '', 'OpCode': 0, 'Ticket': '', 'Sex': 0, 'Scene': 0, 'Signature': '', 'AttrStatus': 0, 'Province': '', 'Alias': '', 'City': '', 'VerifyFlag': 0, 'UserName': ''}, 'HasProductId': 0, 'ForwardFlag': 0, 'SubMsgType': 0}
2017-01-15 21:28:37,991: plugins.eh_telegram_master.TelegramChannel [INFO]
    Got message from queue

2017-01-15 21:28:40,604: plugins.eh_telegram_master.TelegramChannel [DEBUG]
    1484515720.602592, process_msg_step_2
2017-01-15 21:28:40,605: plugins.eh_telegram_master.TelegramChannel [ERROR]
    AttributeError("'NoneType' object has no attribute 'replace'",)Traceback (most recent call last):
  File "/home/xf/repo/ehForwarderBot/plugins/eh_telegram_master/__init__.py", line 287, in process_msg
    html.escape(msg.attributes["description"]))
  File "/home/xf/.pyenv/versions/3.5.2/lib/python3.5/html/__init__.py", line 19, in escape
    s = s.replace("&", "&amp;") # Must be done first!
AttributeError: 'NoneType' object has no attribute 'replace'


```

**Comment by blueset** [comment]
Noted. Fixed in 3d0e458. Will release together with the next version.
