### ISSUE TITLE
can't find config.yaml

### ISSUE THREAD

**Issue by ddqp** [blueset/ehForwarderBot#114]
Pip3安装的，可是找不到这个文件，无法启动。

Traceback (most recent call last):
  File "/usr/local/bin/ehforwarderbot", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/ehforwarderbot/__main__.py", line 161, in main
    init()
  File "/usr/local/lib/python3.6/dist-packages/ehforwarderbot/__main__.py", line 70, in init
    conf = config.load_config()
  File "/usr/local/lib/python3.6/dist-packages/ehforwarderbot/config.py", line 24, in load_config
    raise FileNotFoundError("Config File does not exist. (%s)" % conf_path)
FileNotFoundError: Config File does not exist. (/root/.ehforwarderbot/profiles/default/config.yaml)

**Comment by YHNdnzj** [comment]
請自己創建

**Comment by ddqp** [comment]
这没有教程啊，自己在相应文件夹创建文件后：

Traceback (most recent call last):
  File "/usr/local/bin/ehforwarderbot", line 9, in <module>
    load_entry_point('ehforwarderbot==2.0.0b6', 'console_scripts', 'ehforwarderbot')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/local/lib/python3.6/dist-packages/ehforwarderbot-2.0.0b6-py3.6.egg/ehforwarderbot/__main__.py", line 20, in <module>
  File "/usr/lib/python3.6/gettext.py", line 529, in translation
    raise OSError(ENOENT, 'No translation file found for domain', domain)
FileNotFoundError: [Errno 2] No translation file found for domain: 'ehforwarderbot'

**Comment by YHNdnzj** [comment]
@ddqp更新

**Comment by YHNdnzj** [comment]
新版本已解決

**Comment by ddqp** [comment]
我git pull重新安装后，执行eh，出现如下错误：

·····
Traceback (most recent call last):
  File "/usr/local/bin/ehforwarderbot", line 9, in <module>
    load_entry_point('ehforwarderbot==2.0.0b6', 'console_scripts', 'ehforwarderbot')()
  File "/usr/local/lib/python3.6/dist-packages/ehforwarderbot-2.0.0b6-py3.6.egg/ehforwarderbot/__main__.py", line 169, in main
  File "/usr/local/lib/python3.6/dist-packages/ehforwarderbot-2.0.0b6-py3.6.egg/ehforwarderbot/__main__.py", line 74, in init
  File "/usr/local/lib/python3.6/dist-packages/ehforwarderbot-2.0.0b6-py3.6.egg/ehforwarderbot/config.py", line 33, in load_config
  File "/usr/local/lib/python3.6/dist-packages/ehforwarderbot-2.0.0b6-py3.6.egg/ehforwarderbot/utils.py", line 132, in locate_module
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/local/lib/python3.6/dist-packages/efb_telegram_master-2.0.0b6-py3.6.egg/efb_telegram_master/__init__.py", line 34, in <module>
  File "/usr/local/lib/python3.6/dist-packages/efb_telegram_master-2.0.0b6-py3.6.egg/efb_telegram_master/__init__.py", line 90, in TelegramChannel
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1172, in resource_filename
    self, resource_name
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1717, in get_resource_filename
    return self._extract_resource(manager, zip_path)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1738, in _extract_resource
    timestamp, size = self._get_date_and_size(self.zipinfo[zip_path])
KeyError: 'efb_telegram_master/locale'
`````

**Comment by YHNdnzj** [comment]
我這邊完好

**Comment by YHNdnzj** [comment]
是不是缺依賴

**Comment by ddqp** [comment]
逗正常编译，安装的，requirement里面的pyyaml也安装了，不知道还缺什么

**Comment by YHNdnzj** [comment]
@ddqp不用自己編譯，直接 pip+git 從源碼安裝

**Comment by YHNdnzj** [comment]
還有，可以加入 Telegram 群討論

**Comment by ddqp** [comment]
@YHNdnzj 删除后，这下面安装还是一样的错误：
pip3 install git+https://github.com/blueset/ehForwarderBot.git

**Comment by ddqp** [comment]
@YHNdnzj 请问群地址是？

**Comment by YHNdnzj** [comment]
@ddqphttps://t.me/joinchat/FLrhEECb6bi3x4uoeTfbuA

**Comment by ddqp** [comment]
@YHNdnzj 进去了，好像没人遇到过，谢了

**Comment by silkiller** [comment]
我也遇到相同问题了，你解决了嘛
