### ISSUE TITLE
微信登录报错 peewee.ImproperlyConfigured: SQLite driver not installed!

### ISSUE THREAD

**Issue by 0x0o** [blueset/ehForwarderBot#121]
扫码，手机点击确认登录之后出现一下报错

```
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.4/bin/ehforwarderbot", line 11, in <module>
    sys.exit(main())
  File "/root/.pyenv/versions/3.6.4/lib/python3.6/site-packages/ehforwarderbot/__main__.py", line 190, in main
    init()
  File "/root/.pyenv/versions/3.6.4/lib/python3.6/site-packages/ehforwarderbot/__main__.py", line 94, in init
    (instance_id=instance_id))
  File "/root/.pyenv/versions/3.6.4/lib/python3.6/site-packages/efb_telegram_master/__init__.py", line 124, in __init__
    self.db: DatabaseManager = DatabaseManager(self)
  File "/root/.pyenv/versions/3.6.4/lib/python3.6/site-packages/efb_telegram_master/db.py", line 20, in __init__
    self.db.connect()
  File "/root/.pyenv/versions/3.6.4/lib/python3.6/site-packages/peewee.py", line 2457, in connect
    self._state.set_connection(self._connect())
  File "/root/.pyenv/versions/3.6.4/lib/python3.6/site-packages/peewee.py", line 2689, in _connect
    raise ImproperlyConfigured('SQLite driver not installed!')
peewee.ImproperlyConfigured: SQLite driver not installed!
```

**Comment by Dedsic** [comment]
我碰到并解决了该问题。系统是Debian  
你需要使用pip3或者手动安装pysqlite3。如果是和我一样 [手动安装](https://pypi.python.org/pypi/pysqlite3/0.1.0)，需要同时安装libsqlite3-dev否则会出现缺少库文件的错误导致无法安装。
