### ISSUE TITLE
/link 或者 /chat 时候一直显示processing。

### ISSUE THREAD

**Issue by trefoil01** [blueset/ehForwarderBot#124]
2018-05-03 16:38:00,309 [ERROR]: telegram.ext.dispatcher (dispatcher.process_update; dispatcher.py:301)
    An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "/usr/lib/python3.6/site-packages/telegram/ext/commandhandler.py", line 173, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/usr/lib/python3.6/site-packages/efb_telegram_master/chat_binding.py", line 256, in link_chat_show_list
    return self.link_chat_gen_list(message.from_user.id, pattern=" ".join(args))
  File "/usr/lib/python3.6/site-packages/efb_telegram_master/chat_binding.py", line 408, in link_chat_gen_list
    source_chats=chats)
  File "/usr/lib/python3.6/site-packages/efb_telegram_master/chat_binding.py", line 315, in slave_chats_pagination
    slave_chats = slave.get_chats()
  File "/usr/lib/python3.6/site-packages/efb_wechat_slave/__init__.py", line 544, in get_chats
    return self.chats.get_chats()
  File "/usr/lib/python3.6/site-packages/efb_wechat_slave/chats.py", line 108, in get_chats
    l.append(self.wxpy_chat_to_efb_chat(i))
  File "/usr/lib/python3.6/site-packages/efb_wechat_slave/chats.py", line 68, in wxpy_chat_to_efb_chat
    self.logger.debug("WXPY chat with ID: %s, name: %s, alias: %s;", chat.puid, chat.nick_name, chat.alias)
  File "/usr/lib/python3.6/site-packages/efb_wechat_slave/wxpy/api/chats/chat.py", line 112, in puid
    return self.bot.puid_map.get_puid(self)
  File "/usr/lib/python3.6/site-packages/efb_wechat_slave/wxpy/utils/puid_map.py", line 152, in get_puid
    new_caption = merge_captions(self.captions.get_key(puid), chat_caption)
  File "/usr/lib/python3.6/site-packages/efb_wechat_slave/wxpy/utils/puid_map.py", line 247, in merge_captions
    return tuple(new[i] or old[i] for i in range(4))
  File "/usr/lib/python3.6/site-packages/efb_wechat_slave/wxpy/utils/puid_map.py", line 247, in <genexpr>
    return tuple(new[i] or old[i] for i in range(4))
TypeError: 'NoneType' object is not subscriptable

**Comment by blueset** [comment]
This issue was moved to blueset/efb-wechat-slave#24
