### ISSUE TITLE
2.0 receive/send location raise error

### ISSUE THREAD

**Issue by wolfsilver** [blueset/ehForwarderBot#129]
```
2018-05-11 21:32:17,703 [ERROR]: efb_wechat_slave.wxpy.api.bot (bot.process; bot.py:457) 
    an error occurred in <bound method SlaveMessageManager.Decorators.wechat_msg_meta.<locals>.thread_wrapper of <efb_wechat_slave.slave_message.SlaveMessageManager object at 0x7f564f7c2f98>>.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/efb_wechat_slave/wxpy/api/bot.py", line 453, in process
    ret = config.func(msg)
  File "/usr/local/lib/python3.6/site-packages/efb_wechat_slave/slave_message.py", line 78, in thread_wrapper
    threading.Thread(target=wrap_func, args=args, kwargs=kwargs).run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/site-packages/efb_wechat_slave/slave_message.py", line 72, in wrap_func
    coordinator.send_message(efb_msg)
  File "/usr/local/lib/python3.6/site-packages/ehforwarderbot/coordinator.py", line 103, in send_message
    msg.verify()
  File "/usr/local/lib/python3.6/site-packages/ehforwarderbot/message.py", line 144, in verify
    self.attributes.verify()
  File "/usr/local/lib/python3.6/site-packages/ehforwarderbot/message.py", line 231, in verify
    raise ValueError("Latitude is invalid.")
ValueError: Latitude is invalid.
```

**Comment by blueset** [comment]
This issue was moved to blueset/efb-wechat-slave#26

**Comment by blueset** [comment]
Will be fixed in next version

**Comment by blueset** [comment]
Fixed.
