### ISSUE TITLE
微信登陆成功后收不到任何消息

### ISSUE THREAD

**Issue by Fagurio** [blueset/ehForwarderBot#132]
以下是返回的代码

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/ehforwarderbot/__main__.py", line 195, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/ehforwarderbot/__main__.py", line 190, in main
    init()
  File "/usr/local/lib/python3.6/dist-packages/ehforwarderbot/__main__.py", line 94, in init
    (instance_id=instance_id))
  File "/usr/local/lib/python3.6/dist-packages/efb_telegram_master/__init__.py", line 126, in __init__
    self.voice_recognition: VoiceRecognitionManager = VoiceRecognitionManager(self)
  File "/usr/local/lib/python3.6/dist-packages/efb_telegram_master/voice_recognition.py", line 49, in __init__
    self.voice_engines.append(BaiduSpeech(self.channel, tokens['baidu']))
  File "/usr/local/lib/python3.6/dist-packages/efb_telegram_master/voice_recognition.py", line 116, in __init__
    "client_id": key_dict['api_key'],
TypeError: 'NoneType' object is not subscriptable

**Comment by blueset** [comment]
This issue is not related to the EFB framework. Also, there is a mistake in your Telegram Master channel configuration file which causes this error.
