### ISSUE TITLE
can't receive voice message

### ISSUE THREAD

**Issue by goodosoft** [blueset/ehForwarderBot#133]
**I can see the bot display "recording voice message",but can't really receive it.**

Error information in log:
```
File: <tempfile._TemporaryFileWrapper object at 0x7fcc28137470> (None @ /tmp/tmptry4nj2u), audio/mpeg; Vendor: {}>
JSONDecodeError('Expecting value: line 1 column 1 (char 0)',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/efb_telegram_master/slave_message.py", line 140, in send_message
    elif msg.type == MsgType.File:
  File "/usr/local/lib/python3.6/site-packages/efb_telegram_master/slave_message.py", line 396, in slave_message_audio
    reply_to_message_id=target_msg_id, reply_markup=reply_markup)
  File "/usr/local/lib/python3.6/site-packages/pydub/audio_segment.py", line 658, in from_file
    stdin_data = file.read()
  File "/usr/local/lib/python3.6/site-packages/pydub/utils.py", line 249, in mediainfo_json
    "-show_streams",
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by blueset** [comment]
This issue is not related to EFB framework, module-related issues shall go to their respective repos.

Also, I suspect this issue may be caused by your local `ffmpeg`/`pydub` installation. Please check if you have the proper `ffmpeg` binary installed. Thanks.
