### ISSUE TITLE
在gce上部署efb时出现的错误

### ISSUE THREAD

**Issue by qaz28911971** [blueset/ehForwarderBot#140]
运行 ehforwarder 能正常出现二维码
然后。。
`If the QR code was not shown correctly, please visit:
https://login.weixin.qq.com/qrcode/Ia1bn9aBXw==
Traceback (most recent call last):
  File "/usr/local/bin/ehforwarderbot", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/ehforwarderbot/__main__.py", line 202, in main
    init()
  File "/usr/local/lib/python3.6/dist-packages/ehforwarderbot/__main__.py", line 83, in init
    coordinator.add_channel(cls(instance_id=instance_id))
  File "/usr/local/lib/python3.6/dist-packages/efb_wechat_slave/__init__.py", line 174, in init
    self.authenticate('console_qr_code')
  File "/usr/local/lib/python3.6/dist-packages/efb_wechat_slave/__init__.py", line 519, in authenticate
    logout_callback=self.exit_callback)
  File "/usr/local/lib/python3.6/dist-packages/efb_wechat_slave/wxpy/api/bot.py", line 96, in init
    enhance_webwx_request(self)
  File "/usr/local/lib/python3.6/dist-packages/efb_wechat_slave/wxpy/utils/misc.py", line 327, in enhance_webwx_request
    '&pass_ticket={li[pass_ticket]}'.format(li=login_info)
KeyError: 'wxsid'`

当我再次运行 efb 时，出现了

`root@efb:/home/qaz28911971# ehforwarderbot
2018-09-17 06:56:54,284 [Level 99]: ehforwarderbot.__main__ (__main__.init; main.py:78)
     Initializing slave blueset.wechat...
Traceback (most recent call last):
  File "/usr/local/bin/ehforwarderbot", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/ehforwarderbot/__main__.py", line 202, in main
    init()
  File "/usr/local/lib/python3.6/dist-packages/ehforwarderbot/__main__.py", line 83, in init
    coordinator.add_channel(cls(instance_id=instance_id))
  File "/usr/local/lib/python3.6/dist-packages/efb_wechat_slave/__init__.py", line 174, in init
    self.authenticate('console_qr_code')
  File "/usr/local/lib/python3.6/dist-packages/efb_wechat_slave/__init__.py", line 519, in authenticate
    logout_callback=self.exit_callback)
  File "/usr/local/lib/python3.6/dist-packages/efb_wechat_slave/wxpy/api/bot.py", line 86, in init
    loginCallback=login_callback, exitCallback=logout_callback
  File "/usr/local/lib/python3.6/dist-packages/itchat/components/register.py", line 29, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback):
  File "/usr/local/lib/python3.6/dist-packages/itchat/components/hotreload.py", line 54, in load_login_status
    self.loginInfo['User'] = templates.User(self.loginInfo['User'])
KeyError: 'User'`

**Comment by qaz28911971** [comment]
已经ok了，删除了~/.ehforwarderbot/profiles/default/blueset.wechat/  下的一个文件

**Comment by qaz28911971** [comment]
已经ok了，删除了~/.ehforwarderbot/profiles/default/blueset.wechat/  下的一个文件
