### ISSUE TITLE
why not working?

### ISSUE THREAD

**Issue by ColorfulGhost** [blueset/ehForwarderBot#147]
`Traceback (most recent call last):
  File "main.py", line 135, in <module>
    init()
  File "main.py", line 87, in init
    l.critical("\x1b[0;37;46m Initializing master %s... \x1b[0m" % str(config.master_channel))
AttributeError: module 'config' has no attribute 'master_channel'
23-12-2018:11:16:46,856 CRITICAL [main.py:83]
      Initializing slave ('plugins.eh_wechat_slave', 'WeChatChannel')... 
23-12-2018:11:16:53,747 CRITICAL [main.py:86]
      Slave channel WeChat Slave (eh_wechat_slave) initialized. `

**Comment by ColorfulGhost** [comment]
https://liyuans.com/2018/05/ehforwarderbot.html
