### ISSUE TITLE
some Link type message raise TypeError

### ISSUE THREAD

**Issue by xufan6** [blueset/ehForwarderBot#16]
```
2017-01-22 01:10:07,144: plugins.eh_wechat_slave.WeChatChannel [INFO]
    ---
New Link msg, {'StatusNotifyUserName': '', 'AppMsgType': 5, 'VoiceLength': 0, 'Type': 'Sharing', 'MsgId': '***', 'ImgStatus': 1, 'FromUserName': '@***', 'ImgWidth': 0, 'Url': '', 'RecommendInfo': {'NickName': '', 'Province': '', 'Scene': 0, 'Content': '', 'VerifyFlag': 0, 'AttrStatus': 0, 'Alias': '', 'OpCode': 0, 'Ticket': '', 'City': '', 'Sex': 0, 'QQNum': 0, 'UserName': '', 'Signature': ''}, 'ToUserName': '@***', 'HasProductId': 0, 'MsgType': 49, 'NewMsgId': ***, 'FileName': '交易提醒', 'Ticket': '', 'PlayLength': 0, 'Content': '<msg> <appmsg appid="" sdkver="0"> \t<title><![CDATA[交易提醒]]></title> \t<des><![CDATA[\r\n尊敬的客户:\r\n您的华夏卡****最近交易信息\n\n\n交易时间：22日01时09分\n交易类型：银联银联代付\n交易金额：收款 人民币 ***元\n\r\n您的华夏卡余额为人民币***元。如有疑问，请立即致电***。]]></des> \t<action></action> \t<type>5</type> \t<showtype>1</showtype>     <soundtype>0</soundtype> \t<content><![CDATA[]]></content> \t<contentattr>0</contentattr> \t<url><![CDATA[]]></url> \t<lowurl><![CDATA[]]></lowurl> \t<appattach> \t\t<totallen>0</totallen> \t\t<attachid></attachid> \t\t<fileext></fileext> \t</appattach> \t<extinfo></extinfo> \t<mmreader> \t\t<category type="0" count="1"> \t\t\t<name><![CDATA[华夏银行]]></name> \t\t\t<topnew> \t\t\t\t<cover><![CDATA[]]></cover> \t\t\t\t<width>0</width> \t\t\t\t<height>0</height> \t\t\t\t<digest><![CDATA[\r\n尊敬的客户:\r\n您的华夏卡****最近交易信息\n\n\n交易时间：22日01时09分\n交易类型：银联银联代付\n交易金额：收款 人民币 ***元\n\r\n您的华夏卡余额为人民币***元。如有疑问，请立即致电***。]]></digest> \t\t\t</topnew> \t\t\t\t<item> \t<itemshowtype>4</itemshowtype> \t<title><![CDATA[交易提醒]]></title> \t<url><![CDATA[]]></url> \t<shorturl><![CDATA[]]></shorturl> \t<longurl><![CDATA[]]></longurl> \t<pub_time>1485018604</pub_time> \t<cover><![CDATA[]]></cover> \t<tweetid></tweetid> \t<digest><![CDATA[\r\n尊敬的客户:\r\n您的华夏卡****最近交易信息\n\n\n交易时间：22日01时09分\n交易类型：银联银联代付\n交易金额：收款 人民币 ***元\n\r\n您的华夏卡余额为人民币***元。如有疑问，请立即致电***。]]></digest> \t<fileid>0</fileid> \t<sources> \t<source> \t<name><![CDATA[华夏银行]]></name> \t</source> \t</sources> \t<styles><topColor><![CDATA[#FFFFFF]]></topColor>\n<style>\n<range><![CDATA[{0,26}]]></range>\n<font><![CDATA[s]]></font>\n<color><![CDATA[#000000]]></color>\n</style>\n<style>\n<range><![CDATA[{34,9}]]></range>\n<font><![CDATA[s]]></font>\n<color><![CDATA[#000000]]></color>\n</style>\n<style>\n<range><![CDATA[{49,6}]]></range>\n<font><![CDATA[s]]></font>\n<color><![CDATA[#000000]]></color>\n</style>\n<style>\n<range><![CDATA[{61,14}]]></range>\n<font><![CDATA[s]]></font>\n<color><![CDATA[#0000FF]]></color>\n</style>\n<style>\n<range><![CDATA[{76,39}]]></range>\n<font><![CDATA[s]]></font>\n<color><![CDATA[#000000]]></color>\n</style>\n</styles>\t<native_url></native_url>    <del_flag>0</del_flag>     <contentattr>0</contentattr>     <play_length>0</play_length> \t<play_url></play_url> \t<player><![CDATA[]]></player> \t</item> \t\t</category> \t\t<publisher> \t\t\t<username><![CDATA[hxwxgzzh]]></username> \t\t\t<nickname><![CDATA[华夏银行]]></nickname> \t\t</publisher> \t\t<template_header></template_header> \t\t<template_detail></template_detail> \t    <forbid_forward>0</forbid_forward> \t</mmreader> \t<thumburl><![CDATA[]]></thumburl> \t     <template_id><![CDATA[***]]></template_id>                     </appmsg><fromusername><![CDATA[gh_***]]></fromusername><appinfo><version>0</version><appname><![CDATA[华夏银行]]></appname><isforceupdate>1</isforceupdate></appinfo></msg>', 'AppInfo': {'Type': 0, 'AppID': ''}, 'SubMsgType': 0, 'FileSize': '0', 'CreateTime': 1485018604, 'ImgHeight': 0, 'Status': 3, 'Text': '交易提醒', 'OriContent': '', 'MediaId': '', 'StatusNotifyCode': 0, 'ForwardFlag': 0}
2017-01-22 01:10:07,168: plugins.eh_wechat_slave.incomeMsgMeta [DEBUG]
    me, False
2017-01-22 01:10:07,348: plugins.eh_wechat_slave.incomeMsgMeta [DEBUG]
    From user, {'NickName': '华夏银行', 'VerifyFlag': 24, 'RemarkPYQuanPin': '', 'Alias': 'hxwxgzzh', 'HeadImgUrl': '/cgi-bin/mmwebwx-bin/webwxgeticon?seq=***&username=@***&skey=@***', 'IsOwner': 0, 'MemberList': [], 'UniFriend': 0, 'Statues': 0, 'Uin': 0, 'Sex': 0, 'KeyWord': 'gh_', 'MemberCount': 0, 'RemarkName': '', 'AppAccountFlag': 0, 'OwnerUin': 0, 'DisplayName': '', 'Province': '北京', 'ContactFlag': ***, 'ChatRoomId': 0, 'PYInitial': 'HXYX', 'AttrStatus': 0, 'EncryChatRoomId': '', 'PYQuanPin': 'huaxiayinxing', 'SnsFlag': 0, 'City': '东城', 'RemarkPYInitial': '', 'StarFriend': 0, 'UserName': '@***', 'HideInputBarFlag': 0, 'Signature': '华夏银行'}
2017-01-22 01:10:07,557: plugins.eh_wechat_slave.incomeMsgMeta [DEBUG]
    dest: {'name': '***', 'uid': '***', 'alias': '***'}
2017-01-22 01:10:07,566: plugins.eh_wechat_slave.incomeMsgMeta [INFO]
    WeChat incoming message:
Type: Link
Text: 交易提醒
UserName: @***
uid: ***
name: 华夏银行
2017-01-22 01:10:07,566: plugins.eh_wechat_slave.WeChatChannel [DEBUG]
    WeChat "System" message:
{'Type': 'System', 'ToUserName': '@***', 'FromUserName': '@***', 'Text': ['@@***'], 'SystemInfo': 'chatrooms'}
2017-01-22 01:10:07,567: plugins.eh_telegram_master.TelegramChannel [INFO]
    Got message from queue
Type: Link
Text:
----
2017-01-22 01:10:07,574: plugins.eh_telegram_master.TelegramChannel [DEBUG]
    1485018607.574313, Msg text:
2017-01-22 01:10:07,574: plugins.eh_telegram_master.TelegramChannel [DEBUG]
    1485018607.574313, process_msg_step_0
2017-01-22 01:10:07,574: peewee [DEBUG]
    ('SELECT "t1"."id", "t1"."master_uid", "t1"."slave_uid" FROM "chatassoc" AS t1 WHERE ("t1"."slave_uid" = ?)', ['eh_wechat_slave.***'])
2017-01-22 01:10:07,575: peewee [DEBUG]
    ('SELECT "t1"."id", "t1"."master_uid", "t1"."slave_uid" FROM "chatassoc" AS t1 WHERE ("t1"."master_uid" = ?)', ['eh_telegram_master.-***'])
2017-01-22 01:10:07,575: plugins.eh_telegram_master.TelegramChannel [DEBUG]
    1485018607.574313, process_msg_step_1, tg_dest=***, msg.origin={'name': '华夏银行', 'uid': '***', 'alias': '华夏银行'}
2017-01-22 01:10:07,575: plugins.eh_telegram_master.TelegramChannel [DEBUG]
    1485018607.574313, process_msg_step_2
2017-01-22 01:10:07,575: plugins.eh_telegram_master.TelegramChannel [INFO]
    Msg sent to TG, task_done marked.
2017-01-22 01:10:07,582: plugins.eh_telegram_master.TelegramChannel [ERROR]
    TypeError('quote_from_bytes() expected bytes',)Traceback (most recent call last):
  File "/home/xf/repo/ehForwarderBot/plugins/eh_telegram_master/__init__.py", line 294, in process_msg
    text = "🔗 <a href=\"%s\">%s</a>\n%s" % (urllib.parse.quote(msg.attributes["url"], safe="?=&#:/"),
  File "/home/xf/.pyenv/versions/3.5.2/lib/python3.5/urllib/parse.py", line 712, in quote
    return quote_from_bytes(string, safe)
  File "/home/xf/.pyenv/versions/3.5.2/lib/python3.5/urllib/parse.py", line 737, in quote_from_bytes
    raise TypeError("quote_from_bytes() expected bytes")
TypeError: quote_from_bytes() expected bytes

```

**Comment by blueset** [comment]
Attempt to fix in 1.3.2-dev.6 (64ba954). 
As I can't find messages of the type, please try if it works in the new dev version, or wait for it to be merged to the latest stable one.
