### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by Teddy-Cando** [blueset/ehForwarderBot#169]
After update to lastest version, it not run under python3.6 Ubuntu 18.04
Load Module: Telegram-master, QQ-slave
```
[
Traceback (most recent call last):
  File "/home/tgqq/.local/bin/ehforwarderbot", line 11, in <module>
    sys.exit(main())
  File "/home/tgqq/.local/lib/python3.6/site-packages/ehforwarderbot/__main__.py", line 260, in main
    conf = config.load_config()
  File "/home/tgqq/.local/lib/python3.6/site-packages/ehforwarderbot/config.py", line 56, in load_config
    channel = utils.locate_module(i, 'slave')
  File "/home/tgqq/.local/lib/python3.6/site-packages/ehforwarderbot/utils.py", line 137, in locate_module
    return i.load()
  File "/home/tgqq/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2433, in load
    self.require(*args, **kwargs)
  File "/home/tgqq/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2456, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/tgqq/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (h11 0.9.0 (/home/tgqq/.local/lib/python3.6/site-packages), Requirement.parse('h11~=0.8.1'), {'wsproto'})
]
```

**Comment by blueset** [comment]
This is an issue regarding the dependencies of packages you've installed and [efb-qq-slave](https://github.com/milkice233/efb-qq-slave). Please transfer your issue to `efb-qq-slave` repository for an answer. 

This issue is locked due to irrelevance.
