### ISSUE TITLE
ETM TypeError: quote_from_bytes() expected bytes

### ISSUE THREAD

**Issue by xufan6** [blueset/ehForwarderBot#26]
```
2017-02-21 12:32:09,916: plugins.eh_wechat_slave.wechat_msg_meta [DEBUG]
    Raw message: {'CreateTime': 1487651528, 'PlayLength': 0, 'ImgWidth': 0, 'StatusNotifyUserName': '', 'AppMsgType': 5, 'FromUserName': '@2083930dd3c5xxx', 'ImgStatus': 1, 'AppInfo': {'Type': 0, 'AppID': ''}, 'Type': 'Sharing', 'StatusNotifyCode': 0, 'VoiceLength': 0, 'ForwardFlag': 0, 'ImgHeight': 0, 'Ticket': '', 'FileSize': '0', 'MediaId': '', 'Content': '<msg> <appmsg appid="" sdkver="0"> \t<title><![CDATA[交易提醒]]></title> \t<des><![CDATA[\r\n尊敬的客户:\r\n您的华夏卡*xxx最近交易信息\n\n\n交易时间：21日12时31分\n交易类型：人行跨行收款\n交易金额：收款 人民币 43.84元\n\r\n您的华夏卡余额为人民币2,816.92元。如有疑问，请立即致电95577。]]></des> \t<action></action> \t<type>5</type> \t<showtype>1</showtype>     <soundtype>0</soundtype> \t<content><![CDATA[]]></content> \t<contentattr>0</contentattr> \t<url><![CDATA[]]></url> \t<lowurl><![CDATA[]]></lowurl> \t<appattach> \t\t<totallen>0</totallen> \t\t<attachid></attachid> \t\t<fileext></fileext> \t</appattach> \t<extinfo></extinfo> \t<mmreader> \t\t<category type="0" count="1"> \t\t\t<name><![CDATA[华夏银行]]></name> \t\t\t<topnew> \t\t\t\t<cover><![CDATA[]]></cover> \t\t\t\t<width>0</width> \t\t\t\t<height>0</height> \t\t\t\t<digest><![CDATA[\r\n尊敬的客户:\r\n您的华夏卡*xxx最近交易信息\n\n\n交易时间：21日12时31分\n交易类型：人行跨行收款\n交易金额：收款 人民币 43.84元\n\r\n您的华夏卡余额为人民币2,816.92元。如有疑问，请立即致电95577。]]></digest> \t\t\t</topnew> \t\t\t\t<item> \t<itemshowtype>4</itemshowtype> \t<title><![CDATA[交易提醒]]></title> \t<url><![CDATA[]]></url> \t<shorturl><![CDATA[]]></shorturl> \t<longurl><![CDATA[]]></longurl> \t<pub_time>1487651528</pub_time> \t<cover><![CDATA[]]></cover> \t<tweetid></tweetid> \t<digest><![CDATA[\r\n尊敬的客户:\r\n您的华夏卡*xxx最近交易信息\n\n\n交易时间：21日12时31分\n交易类型：人行跨行收款\n交易金额：收款 人民币 43.84元\n\r\n您的华夏卡余额为人民币2,816.92元。如有疑问，请立即致电95577。]]></digest> \t<fileid>0</fileid> \t<sources> \t<source> \t<name><![CDATA[华夏银行]]></name> \t</source> \t</sources> \t<styles><topColor><![CDATA[#FFFFFF]]></topColor>\n<style>\n<range><![CDATA[{0,26}]]></range>\n<font><![CDATA[s]]></font>\n<color><![CDATA[#000000]]></color>\n</style>\n<style>\n<range><![CDATA[{34,9}]]></range>\n<font><![CDATA[s]]></font>\n<color><![CDATA[#000000]]></color>\n</style>\n<style>\n<range><![CDATA[{49,6}]]></range>\n<font><![CDATA[s]]></font>\n<color><![CDATA[#000000]]></color>\n</style>\n<style>\n<range><![CDATA[{61,13}]]></range>\n<font><![CDATA[s]]></font>\n<color><![CDATA[#0000FF]]></color>\n</style>\n<style>\n<range><![CDATA[{75,39}]]></range>\n<font><![CDATA[s]]></font>\n<color><![CDATA[#000000]]></color>\n</style>\n</styles>\t<native_url></native_url>    <del_flag>0</del_flag>     <contentattr>0</contentattr>     <play_length>0</play_length> \t<play_url></play_url> \t<player><![CDATA[]]></player> \t</item> \t\t</category> \t\t<publisher> \t\t\t<username><![CDATA[hxwxgzzh]]></username> \t\t\t<nickname><![CDATA[华夏银行]]></nickname> \t\t</publisher> \t\t<template_header></template_header> \t\t<template_detail></template_detail> \t    <forbid_forward>0</forbid_forward> \t</mmreader> \t<thumburl><![CDATA[]]></thumburl> \t     <template_id><![CDATA[fkf7nyz4DPQFxxx_g]]></template_id>                     </appmsg><fromusername><![CDATA[gh_4e3aexxx]]></fromusername><appinfo><version>0</version><appname><![CDATA[华夏银行]]></appname><isforceupdate>1</isforceupdate></appinfo></msg>', 'SubMsgType': 0, 'Url': '', 'RecommendInfo': {'Province': '', 'NickName': '', 'Content': '', 'Ticket': '', 'Signature': '', 'Alias': '', 'VerifyFlag': 0, 'Sex': 0, 'QQNum': 0, 'UserName': '', 'OpCode': 0, 'Scene': 0, 'AttrStatus': 0, 'City': ''}, 'Text': '交易提醒', 'Status': 3, 'MsgType': 49, 'HasProductId': 0, 'FileName': '交易提醒', 'OriContent': '', 'NewMsgId': 883399138xxx, 'ToUserName': '@099639dbd19fabcxxx', 'MsgId': '883399138xxx'}
2017-02-21 12:32:09,917: plugins.eh_wechat_slave.wechat_msg_meta [DEBUG]
    Raw message: {'CreateTime': 1487651528, 'PlayLength': 0, 'ImgWidth': 0, 'StatusNotifyUserName': '', 'AppMsgType': 5, 'FromUserName': '@2083930dd3c5xxx', 'ImgStatus': 1, 'AppInfo': {'Type': 0, 'AppID': ''}, 'Type': 'Sharing', 'StatusNotifyCode': 0, 'VoiceLength': 0, 'ForwardFlag': 0, 'ImgHeight': 0, 'Ticket': '', 'FileSize': '0', 'MediaId': '', 'Content': '<msg> <appmsg appid="" sdkver="0"> \t<title><![CDATA[交易提醒]]></title> \t<des><![CDATA[\r\n尊敬的客户:\r\n您的华夏卡*xxx最近交易信息\n\n\n交易时间：21日12时31分\n交易类型：人行跨行收款\n交易金额：收款 人民币 43.84元\n\r\n您的华夏卡余额为人民币2,816.92元。如有疑问，请立即致电95577。]]></des> \t<action></action> \t<type>5</type> \t<showtype>1</showtype>     <soundtype>0</soundtype> \t<content><![CDATA[]]></content> \t<contentattr>0</contentattr> \t<url><![CDATA[]]></url> \t<lowurl><![CDATA[]]></lowurl> \t<appattach> \t\t<totallen>0</totallen> \t\t<attachid></attachid> \t\t<fileext></fileext> \t</appattach> \t<extinfo></extinfo> \t<mmreader> \t\t<category type="0" count="1"> \t\t\t<name><![CDATA[华夏银行]]></name> \t\t\t<topnew> \t\t\t\t<cover><![CDATA[]]></cover> \t\t\t\t<width>0</width> \t\t\t\t<height>0</height> \t\t\t\t<digest><![CDATA[\r\n尊敬的客户:\r\n您的华夏卡*xxx最近交易信息\n\n\n交易时间：21日12时31分\n交易类型：人行跨行收款\n交易金额：收款 人民币 43.84元\n\r\n您的华夏卡余额为人民币2,816.92元。如有疑问，请立即致电95577。]]></digest> \t\t\t</topnew> \t\t\t\t<item> \t<itemshowtype>4</itemshowtype> \t<title><![CDATA[交易提醒]]></title> \t<url><![CDATA[]]></url> \t<shorturl><![CDATA[]]></shorturl> \t<longurl><![CDATA[]]></longurl> \t<pub_time>1487651528</pub_time> \t<cover><![CDATA[]]></cover> \t<tweetid></tweetid> \t<digest><![CDATA[\r\n尊敬的客户:\r\n您的华夏卡*xxx最近交易信息\n\n\n交易时间：21日12时31分\n交易类型：人行跨行收款\n交易金额：收款 人民币 43.84元\n\r\n您的华夏卡余额为人民币2,816.92元。如有疑问，请立即致电95577。]]></digest> \t<fileid>0</fileid> \t<sources> \t<source> \t<name><![CDATA[华夏银行]]></name> \t</source> \t</sources> \t<styles><topColor><![CDATA[#FFFFFF]]></topColor>\n<style>\n<range><![CDATA[{0,26}]]></range>\n<font><![CDATA[s]]></font>\n<color><![CDATA[#000000]]></color>\n</style>\n<style>\n<range><![CDATA[{34,9}]]></range>\n<font><![CDATA[s]]></font>\n<color><![CDATA[#000000]]></color>\n</style>\n<style>\n<range><![CDATA[{49,6}]]></range>\n<font><![CDATA[s]]></font>\n<color><![CDATA[#000000]]></color>\n</style>\n<style>\n<range><![CDATA[{61,13}]]></range>\n<font><![CDATA[s]]></font>\n<color><![CDATA[#0000FF]]></color>\n</style>\n<style>\n<range><![CDATA[{75,39}]]></range>\n<font><![CDATA[s]]></font>\n<color><![CDATA[#000000]]></color>\n</style>\n</styles>\t<native_url></native_url>    <del_flag>0</del_flag>     <contentattr>0</contentattr>     <play_length>0</play_length> \t<play_url></play_url> \t<player><![CDATA[]]></player> \t</item> \t\t</category> \t\t<publisher> \t\t\t<username><![CDATA[hxwxgzzh]]></username> \t\t\t<nickname><![CDATA[华夏银行]]></nickname> \t\t</publisher> \t\t<template_header></template_header> \t\t<template_detail></template_detail> \t    <forbid_forward>0</forbid_forward> \t</mmreader> \t<thumburl><![CDATA[]]></thumburl> \t     <template_id><![CDATA[fkf7nyz4DPQFxxx_g]]></template_id>                     </appmsg><fromusername><![CDATA[gh_4e3aexxx]]></fromusername><appinfo><version>0</version><appname><![CDATA[华夏银行]]></appname><isforceupdate>1</isforceupdate></appinfo></msg>', 'SubMsgType': 0, 'Url': '', 'RecommendInfo': {'Province': '', 'NickName': '', 'Content': '', 'Ticket': '', 'Signature': '', 'Alias': '', 'VerifyFlag': 0, 'Sex': 0, 'QQNum': 0, 'UserName': '', 'OpCode': 0, 'Scene': 0, 'AttrStatus': 0, 'City': ''}, 'Text': '交易提醒', 'Status': 3, 'MsgType': 49, 'HasProductId': 0, 'FileName': '交易提醒', 'OriContent': '', 'NewMsgId': 883399138xxx, 'ToUserName': '@099639dbd19fabcxxx', 'MsgId': '883399138xxx'}
2017-02-21 12:32:09,917: plugins.eh_wechat_slave.wechat_msg_meta [DEBUG]
    me, False
2017-02-21 12:32:10,021: plugins.eh_wechat_slave.wechat_msg_meta [DEBUG]
    From user, {'Province': '北京', 'HideInputBarFlag': 0, 'StarFriend': 0, 'HeadImgUrl': '/cgi-bin/mmwebwx-bin/webwxgeticon?seq=653066722&username=@2083930dd3c5xxx&skey=@crypt_2fa3b0c2_45d54fxxx', 'PYInitial': 'HXYX', 'ChatRoomId': 0, 'UserName': '@2083930dd3c5xxx', 'Alias': 'hxwxgzzh', 'UniFriend': 0, 'Uin': 'gh_4e3aexxx', 'IsOwner': 0, 'AppAccountFlag': 0, 'SnsFlag': 0, 'NickName': '华夏银行', 'City': '东城', 'Sex': 0, 'MemberCount': 0, 'RemarkPYQuanPin': '', 'EncryChatRoomId': '', 'RemarkName': '', 'ContactFlag': 2051, 'VerifyFlag': 24, 'RemarkPYInitial': '', 'KeyWord': 'gh_', 'AttrStatus': 0, 'Signature': '华夏银行', 'PYQuanPin': 'huaxiayinxing', 'MemberList': [], 'Statues': 0, 'OwnerUin': 0, 'DisplayName': ''}
2017-02-21 12:32:10,116: plugins.eh_wechat_slave.wechat_msg_meta [DEBUG]
    dest: {'uid': '69049xxx', 'alias': 'xufan6', 'name': 'xufan6'}
2017-02-21 12:32:10,117: plugins.eh_wechat_slave.wechat_msg_meta [INFO]
    WeChat incoming message:
Type: Link
Text: 交易提醒
UserName: @2083930dd3c5xxx
uid: xxx
name: 华夏银行
2017-02-21 12:32:10,117: plugins.eh_telegram_master.TelegramChannel [INFO]
    Got message from queue
Type: Link
Text:
----
2017-02-21 12:32:10,117: plugins.eh_telegram_master.TelegramChannel [DEBUG]
    1487651530.117628, Msg text:
2017-02-21 12:32:10,117: plugins.eh_telegram_master.TelegramChannel [INFO]
    Msg sent to TG, task_done marked.
2017-02-21 12:32:10,117: plugins.eh_telegram_master.TelegramChannel [DEBUG]
    1487651530.117628, process_msg_step_0
2017-02-21 12:32:10,118: peewee [DEBUG]
    ('SELECT "t1"."id", "t1"."master_uid", "t1"."slave_uid" FROM "chatassoc" AS t1 WHERE ("t1"."slave_uid" = ?)', ['eh_wechat_slave.xxx'])
2017-02-21 12:32:10,118: peewee [DEBUG]
    ('SELECT "t1"."id", "t1"."master_uid", "t1"."slave_uid" FROM "chatassoc" AS t1 WHERE ("t1"."master_uid" = ?)', ['eh_telegram_master.-1813xxx'])
2017-02-21 12:32:10,119: plugins.eh_telegram_master.TelegramChannel [DEBUG]
    1487651530.117628, process_msg_step_1, tg_dest=xxx, msg.origin={'uid': 'xxx', 'alias': '华夏银行', 'name': '华夏银行'}
2017-02-21 12:32:10,119: plugins.eh_telegram_master.TelegramChannel [DEBUG]
    1487651530.117628, process_msg_step_2
2017-02-21 12:32:10,120: plugins.eh_telegram_master.TelegramChannel [ERROR]
    TypeError('quote_from_bytes() expected bytes',)Traceback (most recent call last):
  File "/home/xf/repo/ehForwarderBot/plugins/eh_telegram_master/__init__.py", line 304, in process_msg
    urllib.parse.quote(msg.attributes["url"], safe="?=&#:/"),
  File "/home/xf/.pyenv/versions/3.5.2/lib/python3.5/urllib/parse.py", line 712, in quote
    return quote_from_bytes(string, safe)
  File "/home/xf/.pyenv/versions/3.5.2/lib/python3.5/urllib/parse.py", line 737, in quote_from_bytes
    raise TypeError("quote_from_bytes() expected bytes")
TypeError: quote_from_bytes() expected bytes
```

**Comment by blueset** [comment]
Fixed in 1.5.2 (f72c836).
