### ISSUE TITLE
No module named 'pyqrcode'

### ISSUE THREAD

**Issue by MitsuhaMiyamizu** [blueset/ehForwarderBot#31]
I installed python-pyqrcode-5.3-3 on Arch Linux but it encountered the problem below:
```
pid: 17896
   Output is saved to 'EFB.log', showing output now.       
   Press ^C (Control+C on Mac, Ctrl+C otherwise) to hide.  

2017-03-03 11:05:03,566: ehForwarderBot [CRITICAL]
     Initializing slave ('plugins.eh_wechat_slave', 'WeChatChannel')... 
Traceback (most recent call last):
  File "main.py", line 131, in <module>
    init()
  File "main.py", line 83, in init
    obj = getattr(__import__(i[0], fromlist=i[1]), i[1])
  File "/home/alex/ehForwarderBot/plugins/eh_wechat_slave.py", line 15, in <module>
    from pyqrcode import QRCode
ModuleNotFoundError: No module named 'pyqrcode'
```
This is definately a serious bug.

**Comment by blueset** [comment]
@MitsuhaMiyamizu Please try to install it with the correct pip (usually pip3). A good way is to use the available requirements.txt to upgrade all Python dependencies.

**Comment by MitsuhaMiyamizu** [comment]
thanks, problem solved

**Comment by PatelAman17** [comment]
Still I have the problem can you help in it
