### ISSUE TITLE
/link 的时候报错。

### ISSUE THREAD

**Issue by DrayChou** [blueset/ehForwarderBot#32]
执行命令 /link 的时候报下面的错误：

2017-03-08 10:27:01,948: telegram.ext.dispatcher [ERROR]
    An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/telegram/ext/dispatcher.py", line 270, in process_update
    handler.handle_update(update, self)
  File "/usr/local/lib/python3.4/dist-packages/telegram/ext/commandhandler.py", line 100, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/srv/approot/ehForwarderBot/plugins/eh_telegram_master/__init__.py", line 671, in link_chat_show_list
    self.link_chat_gen_list(bot, update.message.from_user.id, filter=" ".join(args))
  File "/srv/approot/ehForwarderBot/plugins/eh_telegram_master/__init__.py", line 697, in link_chat_gen_list
    fchats=chats)
  File "/srv/approot/ehForwarderBot/plugins/eh_telegram_master/__init__.py", line 532, in slave_chats_pagination
    slave_chats = slave.get_chats()
  File "/srv/approot/ehForwarderBot/plugins/eh_wechat_slave.py", line 899, in get_chats
    Uin=i.get("Uin", None)),
  File "/srv/approot/ehForwarderBot/plugins/eh_wechat_slave.py", line 255, in get_uid
    data = {"nickname": r[0]['NickName'], "alias": r[0]["RemarkName"], "uin": r[0]["Uin"]}
KeyError: 'Uin'

**Comment by blueset** [comment]
@DrayChou 尝试登出微信后重新登录后是否能够重现。

**Comment by DrayChou** [comment]
重新绑定解绑是好了，这个是因为联系人过多吗？
还是因为微信修改了协议？

Eana Hufwe <notifications@github.com> 於 2017年3月8日 週三 下午6:41寫道：

**Comment by blueset** [comment]
@DrayChou 微信网页版协议完全是玄学。各种问题只有重置才能解决。

**Comment by DrayChou** [comment]
这个...
神奇。
好吧，那先这样吧。谢谢


Eana Hufwe <notifications@github.com> 於 2017年3月9日 週四 下午2:10寫道：
