### ISSUE TITLE
无法接收图片和语音消息（可以发送）

### ISSUE THREAD

**Issue by martixingwei** [blueset/ehForwarderBot#35]
我手动开了debug之后的输出是
语音消息：
```
2017-03-18 18:56:49,272: plugins.eh_wechat_slave.wechat_msg_meta [DEBUG]
    Raw message: {'Content': '<msg><voicemsg endflag="1" cancelflag="0" forwardflag="0" voiceformat="4" voicelength="2281" length="4181" bufid="*****" clientmsgid="*****" fromusername="*****" /></msg>', 'MsgId': '*****', 'CreateTime': 1489863408, 'ImgWidth': 0, 'RecommendInfo': {'VerifyFlag': 0, 'Content': '', 'UserName': '', 'City': '', 'Signature': '', 'NickName': '', 'Sex': 0, 'Alias': '', 'Scene': 0, 'Ticket': '', 'Province': '', 'AttrStatus': 0, 'QQNum': 0, 'OpCode': 0}, 'OriContent': '', 'Type': 'Recording', 'StatusNotifyCode': 0, 'StatusNotifyUserName': '', 'FileSize': '', 'MediaId': '', 'Text': <function get_download_fn.<locals>.download_fn at 0x7f525019b158>, 'VoiceLength': 2281, 'FileName': '*****-*****.mp3', 'ImgHeight': 0, 'NewMsgId': *****, 'Status': 3, 'ForwardFlag': 0, 'AppMsgType': 0, 'Url': '', 'FromUserName': '@*****', 'PlayLength': 0, 'ToUserName': 'filehelper', 'HasProductId': 0, 'ImgStatus': 1, 'SubMsgType': 0, 'Ticket': '', 'MsgType': 34, 'AppInfo': {'AppID': '', 'Type': 0}}
2017-03-18 18:56:49,369: itchat [WARNING]
    Traceback (most recent call last):
  File "/home/*****/.local/lib/python3.5/site-packages/itchat/components/register.py", line 66, in configured_reply
    r = replyFn(msg)
  File "/home/*****/ehForwarderBot/plugins/eh_wechat_slave.py", line 29, in wrap_func
    mobj = func(self, msg, *args, **kwargs)
  File "/home/*****/ehForwarderBot/plugins/eh_wechat_slave.py", line 516, in wechat_voice_msg
    mobj.path, mobj.mime = self.save_file(msg, mobj.type)
  File "/home/*****/ehForwarderBot/plugins/eh_wechat_slave.py", line 594, in save_file
    msg['Text'](fullpath)
  File "/home/*****/.local/lib/python3.5/site-packages/itchat/components/messages.py", line 42, in download_fn
    'PostFix': utils.get_image_postfix(tempStorage.read(20)), })
  File "/home/*****/.local/lib/python3.5/site-packages/itchat/utils.py", line 137, in get_image_postfix
    if 'GIF' in data:
TypeError: a bytes-like object is required, not 'str'
```
图片消息：
```
2017-03-18 18:55:59,914: plugins.eh_wechat_slave.wechat_msg_meta [DEBUG]
    Raw message: {'Content': '<?xml version="1.0"?>\n<msg>\n\t<img aeskey="*****" encryver="0" cdnthumbaeskey="*****" cdnthumburl="*****" cdnthumblength="6534" cdnthumbheight="120" cdnthumbwidth="68" cdnmidheight="0" cdnmidwidth="0" cdnhdheight="0" cdnhdwidth="0" cdnmidimgurl="*****" length="41313" md5="*****" />\n</msg>\n', 'MsgId': '*****', 'CreateTime': 1489863359, 'ImgWidth': 68, 'RecommendInfo': {'VerifyFlag': 0, 'Content': '', 'UserName': '', 'City': '', 'Signature': '', 'NickName': '', 'Sex': 0, 'Alias': '', 'Scene': 0, 'Ticket': '', 'Province': '', 'AttrStatus': 0, 'QQNum': 0, 'OpCode': 0}, 'OriContent': '', 'Type': 'Picture', 'StatusNotifyCode': 0, 'StatusNotifyUserName': '', 'FileSize': '', 'MediaId': '', 'Text': <function get_download_fn.<locals>.download_fn at 0x7f5250187950>, 'VoiceLength': 0, 'FileName': '*****.png', 'ImgHeight': 120, 'NewMsgId': *****, 'Status': 3, 'ForwardFlag': 0, 'AppMsgType': 0, 'Url': '', 'FromUserName': '@*****', 'PlayLength': 0, 'ToUserName': 'filehelper', 'HasProductId': 0, 'ImgStatus': 2, 'SubMsgType': 0, 'Ticket': '', 'MsgType': 3, 'AppInfo': {'AppID': '', 'Type': 0}}
2017-03-18 18:56:00,766: itchat [WARNING]
    Traceback (most recent call last):
  File "/home/*****/.local/lib/python3.5/site-packages/itchat/components/register.py", line 66, in configured_reply
    r = replyFn(msg)
  File "/home/*****/ehForwarderBot/plugins/eh_wechat_slave.py", line 29, in wrap_func
    mobj = func(self, msg, *args, **kwargs)
  File "/home/*****/ehForwarderBot/plugins/eh_wechat_slave.py", line 496, in wechat_picture_msg
    mobj.path, mime = self.save_file(msg, mobj.type)
  File "/home/*****/ehForwarderBot/plugins/eh_wechat_slave.py", line 594, in save_file
    msg['Text'](fullpath)
  File "/home/*****/.local/lib/python3.5/site-packages/itchat/components/messages.py", line 42, in download_fn
    'PostFix': utils.get_image_postfix(tempStorage.read(20)), })
  File "/home/*****/.local/lib/python3.5/site-packages/itchat/utils.py", line 137, in get_image_postfix
    if 'GIF' in data:
TypeError: a bytes-like object is required, not 'str'
```

另外发送语音消息对面收到的是个****.unknown文件，这是设计如此还是Bug？

**Comment by blueset** [comment]
该问题为上游库的 Bug（littlecodersh/itchat#334）。

> 另外发送语音消息对面收到的是个****.unknown文件，这是设计如此还是Bug？
这个应该是 libmagic 库造成的问题。不过微信本身不支持发送语音，即使扩展名正确也有可能无法播放 ogg (opus)。

**Comment by littlecodersh** [comment]
@martixingwei @blueset 我的锅，更版本的时候测了两遍py2。
更新itchat 1.2.32即可：
```python
pip install itchat -U
```

**Comment by martixingwei** [comment]
@littlecodersh 现在最新的还是1.2.31

**Comment by littlecodersh** [comment]
@martixingwei 稍等一下再更新或者到[pypi][1.3.0]下载吧。

[1.3.0]: https://pypi.python.org/pypi?:action=display&name=itchat&version=1.2.32
