### ISSUE TITLE
登陆成功但无法接收消息

### ISSUE THREAD

**Issue by tinnelly** [blueset/ehForwarderBot#41]
配置成功后，也扫描了二维码，显示登录成功
`Successfully authorized.`

接着弹出：
`Traceback (most recent call last):
  File "main.py", line 131, in <module>
    init()
  File "main.py", line 88, in init
    q, mutex, slaves)
  File "/home/rsa-key-20170406/ehForwarderBot/plugins/eh_telegram_master/__init__.py", line 122, in __init__
    self.me = self.bot.bot.get_me()
  File "/home/rsa-key-20170406/.local/lib/python3.5/site-packages/telegram/bot.py", line 125, in decorator
    result = func(self, *args, **kwargs)
  File "/home/rsa-key-20170406/.local/lib/python3.5/site-packages/telegram/bot.py", line 174, in getMe
    result = self._request.get(url)
  File "/home/rsa-key-20170406/.local/lib/python3.5/site-packages/telegram/utils/request.py", line 170, in get
    result = self._request_wrapper('GET', url)
  File "/home/rsa-key-20170406/.local/lib/python3.5/site-packages/telegram/utils/request.py", line 150, in _request_wrapper
    raise Unauthorized()
telegram.error.Unauthorized: Unauthorized`

试了试发了消息没反应

**Comment by blueset** [comment]
请检查你的 `config.py` 里面的配置，尤其是 Bot 的 token 是否正确。
