### ISSUE TITLE
Telegram端无法发送消息

### ISSUE THREAD

**Issue by gaoyifan** [blueset/ehForwarderBot#52]
【表现】
持续运行数天后，随机出现telegram.error.TelegramError: Invalid server response错误，表现为telegram可以接收到WeChat消息，但无法发送消息（即：Telegram端显示消息已读，WeChat实际没发出去）。
重启ehForwarderBot后立刻恢复正常。如果不重启，将会长时间保持无法发送消息的状态。
未观察到该错误与某些操作有确定性关联。

尝试更换了服务器（从新加坡换到了洛杉矶），似乎并没有效果。

【环境】
ehForwarderBot版本：1.6.1
Python版本：3.6.1
OS：alpine edge
Docker镜像：[gaoyifan/ehforwarderbot](https://hub.docker.com/r/gaoyifan/ehforwarderbot/)

【错误日志】
```
Exception in thread dispatcher:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/telegram/utils/request.py", line 98, in _parse
    data = json.loads(decoded_s)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/site-packages/telegram/ext/updater.py", line 115, in _thread_wrapper
    target(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 219, in start
    self.process_update(update)
  File "/usr/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 263, in process_update
    self.dispatch_error(None, update)
  File "/usr/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 374, in dispatch_error
    callback(self.bot, update, error)
  File "/opt/ehForwarderBot/plugins/eh_telegram_master/__init__.py", line 1638, in error
    (html.escape(str(error)), html.escape(str(update))))
  File "/usr/lib/python3.6/site-packages/telegram/bot.py", line 125, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/telegram/bot.py", line 151, in decorator
    result = self._request.post(url, data, timeout=kwargs.get('timeout'))
  File "/usr/lib/python3.6/site-packages/telegram/utils/request.py", line 207, in post
    **urlopen_kwargs)
  File "/usr/lib/python3.6/site-packages/telegram/utils/request.py", line 145, in _request_wrapper
    message = self._parse(resp.data)
  File "/usr/lib/python3.6/site-packages/telegram/utils/request.py", line 100, in _parse
    raise TelegramError('Invalid server response')
telegram.error.TelegramError: Invalid server response
```
完整日志：
[ehforwarderbot.log.txt](https://github.com/blueset/ehForwarderBot/files/1049377/ehforwarderbot.log.txt)

**Comment by blueset** [comment]
将在下一版本尝试修复这一问题。

**Comment by blueset** [comment]
已于 1.6.2 尝试修复此问题。

**Comment by gaoyifan** [comment]
感谢您的帮助！ 
测试了48小时，故障未复现。我将关闭这个issue。

**Comment by Jack-Works** [comment]
感谢作者的劳动，我也经常出现这一问题，现在来追着 git log 看记录发现修了
