### ISSUE TITLE
无法发送图片消息

### ISSUE THREAD

**Issue by iarchean** [blueset/ehForwarderBot#69]
具体表现为，Telegram 上发送成功，微信上无法收到，DEBUG 信息如下：

2017-07-28 09:14:36,946: telegram.ext.dispatcher [DEBUG]
    Processing Update: {略去}
2017-07-28 09:14:36,947: telegram.ext.dispatcher [ERROR]
    An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/home/archean/.local/lib/python3.5/site-packages/telegram/ext/dispatcher.py", line 269, in process_update
    if handler.check_update(update):
  File "/home/archean/.local/lib/python3.5/site-packages/telegram/ext/regexhandler.py", line 150, in check_update
    match = re.match(self.pattern, update.effective_message.text)
  File "/usr/lib/python3.5/re.py", line 163, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or bytes-like object

**Comment by Bbbzhao** [comment]
同样遇到这个问题

**Comment by blueset** [comment]
请尝试更新 `python-telegram-bot` 到最新版本。

**Comment by newdee** [comment]
突然又无法发送图片了，之前用着一直好好的，昨天晚上开始无法发送图片，发送图片则显示'wechat server logged out the user', 然后要求重新登录，重新登录后再发送图片，又是这个提示。 微信端也无法看到图片。  
所使用的是docker版本，重启docker容器也是一样。
