### ISSUE TITLE
a few days later.when i input chat command. bot is not respond

### ISSUE THREAD

**Issue by laihuchun** [blueset/ehForwarderBot#72]
errlog :
2017-08-09 06:32:20,938: telegram.ext.dispatcher [ERROR]
    An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.5/site-packages/telegram/ext/dispatcher.py", line 265, in process_update
    handler.handle_update(update, self)
  File "/usr/local/python3/lib/python3.5/site-packages/telegram/ext/commandhandler.py", line 136, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/root/ehForwarderBot/plugins/eh_telegram_master/__init__.py", line 907, in start_chat_list
    self.chat_head_req_generate(bot, target, filter=" ".join(args), chats=chats)
  File "/root/ehForwarderBot/plugins/eh_telegram_master/__init__.py", line 957, in chat_head_req_generate
    legend, chat_btn_list = self.slave_chats_pagination("%s.%s" % (chat_id, message_id), offset, filter=filter, fchats=chats)
  File "/root/ehForwarderBot/plugins/eh_telegram_master/__init__.py", line 534, in slave_chats_pagination
    slave_chats = slave.get_chats()
  File "/root/ehForwarderBot/plugins/eh_wechat_slave.py", line 899, in get_chats
    Uin=i.get("Uin", None)),
  File "/root/ehForwarderBot/plugins/eh_wechat_slave.py", line 255, in get_uid
    data = {"nickname": r[0]['NickName'], "alias": r[0]["RemarkName"], "uin": r[0]["Uin"]}
KeyError: 'Uin'

doc descripts

"uin": [UG] WeChat Unique Identifier for all chats, Not always available.
Only recommended for those with "Uin rate" higher than 90% in most cases. Check Uin rate with the  check_uin command.

**Comment by blueset** [comment]
This issue should be fixed in the latest version. Please try to upgrade first.
