### ISSUE TITLE
telegram.ext.dispatcher [ERROR]

### ISSUE THREAD

**Issue by johnpoint** [blueset/ehForwarderBot#76]
2017-08-24 23:47:04,483: telegram.ext.dispatcher [ERROR]
    An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telegram/ext/dispatcher.py", line 270, in process_update
    handler.handle_update(update, self)
  File "/usr/local/lib/python3.5/dist-packages/telegram/ext/commandhandler.py", line 172, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/root/ehForwarderBot/plugins/eh_telegram_master/__init__.py", line 907, in start_chat_list
    self.chat_head_req_generate(bot, target, filter=" ".join(args), chats=chats)
  File "/root/ehForwarderBot/plugins/eh_telegram_master/__init__.py", line 957, in chat_head_req_generate
    legend, chat_btn_list = self.slave_chats_pagination("%s.%s" % (chat_id, message_id), offset, filter=filter, fchats=chats)
  File "/root/ehForwarderBot/plugins/eh_telegram_master/__init__.py", line 534, in slave_chats_pagination
    slave_chats = slave.get_chats()
  File "/root/ehForwarderBot/plugins/eh_wechat_slave.py", line 874, in get_chats
    if i['UserName'] == self.itchat.loginInfo['User']['UserName']:
KeyError: 'User'
系统：Ubuntu 16.04 x86_64  
安装完后，发/chat给bot出现，
附图：
![image](https://user-images.githubusercontent.com/24842848/29698971-d8ce4d76-898b-11e7-80a9-3c3c3115ed85.png)
![image](https://user-images.githubusercontent.com/24842848/29698979-eedc53b0-898b-11e7-8872-9b63e79c20b9.png)

**Comment by johnpoint** [comment]
估计是微信那边限制了链接

**Comment by johnpoint** [comment]
换了一个ip排除ip封锁的可能
等会再测试下不同账户

**Comment by blueset** [comment]
Possible duplicate #74

**Comment by johnpoint** [comment]
ok

**Comment by johnpoint** [comment]
I can't log in by Web version of WeChat
