### ISSUE TITLE
Failed after scanning the login qr code

### ISSUE THREAD

**Issue by Jack-Works** [blueset/ehForwarderBot#77]
Log: (after scan the code on wechat)
```
Traceback (most recent call last):
  File "main.py", line 132, in <module>
    init()
  File "main.py", line 84, in init
    slaves[obj.channel_id] = obj(q, mutex)
  File "/home/jack/ehForwarderBot/plugins/eh_wechat_slave.py", line 127, in __init__
    qrCallback=self.console_qr_code)
  File "/home/jack/.local/lib/python3.5/site-packages/itchat/components/register.py", line 32, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "/home/jack/.local/lib/python3.5/site-packages/itchat/components/login.py", line 49, in login
    status = self.check_login()
  File "/home/jack/.local/lib/python3.5/site-packages/itchat/components/login.py", line 132, in check_login
    process_login_info(self, r.text)
  File "/home/jack/.local/lib/python3.5/site-packages/itchat/components/login.py", line 165, in process_login_info
    for node in xml.dom.minidom.parseString(r.text).documentElement.childNodes:
  File "/usr/lib/python3.5/xml/dom/minidom.py", line 1968, in parseString
    return expatbuilder.parseString(string)
  File "/usr/lib/python3.5/xml/dom/expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
  File "/usr/lib/python3.5/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: no element found: line 1, column 0
```

**Comment by blueset** [comment]
Please check that you can still access Web WeChat with your browser.

If you are banned from using Web WeChat, refer to [this wiki article](https://github.com/blueset/ehForwarderBot/wiki/EWS:-Current-reports-regarding-potential-actions-that-triggers-Web-WeChat-ban) for details.

**Comment by Jack-Works** [comment]
<error><ret>1203</ret><message>当前登录环境异常。为了你的帐号安全，暂时不能登录web微信。你可以通过手机客户端或者windows微信登录。</message></error>
