### ISSUE TITLE
登陆遇到错误

### ISSUE THREAD

**Issue by fondoger** [blueset/ehForwarderBot#81]
```
If you cannot read the QR code above, please visit the following URL:
https://login.weixin.qq.com/qrcode/IcwMviiHQw==
2017-09-11 19:17:34,104: plugins.eh_wechat_slave.WeChatChannel [CRITICAL]
    Tap "Confirm" to continue.
2017-09-11 19:17:37,110: plugins.eh_wechat_slave.WeChatChannel [CRITICAL]
    Successfully authorized.
2017-09-11 19:17:41,700: ehForwarderBot [CRITICAL]
     Slave channel WeChat Slave (eh_wechat_slave) initialized.
2017-09-11 19:17:41,701: ehForwarderBot [CRITICAL]
     Initializing master ('plugins.eh_telegram_master', 'TelegramChannel')...
2017-09-11 19:17:42,910: ehForwarderBot [CRITICAL]
     Master channel Telegram Master (eh_telegram_master) initialized.
2017-09-11 19:17:42,911: ehForwarderBot [CRITICAL]
     All channels initialized.

2017-09-11 19:20:28,155: plugins.eh_telegram_master.TelegramChannel [ERROR]
    BadRequest()Traceback (most recent call last):
  File "/root/ehForwarderBot/plugins/eh_telegram_master/__init__.py", line 284, in process_msg
    self.bot.bot.send_chat_action(tg_dest, telegram.ChatAction.TYPING)
  File "/usr/local/lib/python3.5/dist-packages/telegram/bot.py", line 57, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/telegram/bot.py", line 1029, in send_chat_action
    result = self._request.post(url, data, timeout=timeout)
  File "/usr/local/lib/python3.5/dist-packages/telegram/utils/request.py", line 271, in post
    **urlopen_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/telegram/utils/request.py", line 209, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Chat not found

```

**Comment by fondoger** [comment]
是不是网络的问题啊？
我用的是digital ocean的旧金山服务器。

**Comment by blueset** [comment]
请检查 Admin ID 是否设置正确。
