### ISSUE TITLE
扫码之后报错 timeout

### ISSUE THREAD

**Issue by Hexor** [blueset/ehForwarderBot#83]
Traceback (most recent call last):
  File "/home/hexor/.local/lib/python3.5/site-packages/telegram/vendor/ptb_urllib3/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/home/hexor/.local/lib/python3.5/site-packages/telegram/vendor/ptb_urllib3/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/home/hexor/.local/lib/python3.5/site-packages/telegram/vendor/ptb_urllib3/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hexor/.local/lib/python3.5/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 617, in urlopen
    chunked=chunked)
  File "/home/hexor/.local/lib/python3.5/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 360, in _make_request
    self._validate_conn(conn)
  File "/home/hexor/.local/lib/python3.5/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 857, in _validate_conn
    super(HTTPSConnectionPool, self)._validate_conn(conn)
  File "/home/hexor/.local/lib/python3.5/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 289, in _validate_conn
    conn.connect()
  File "/home/hexor/.local/lib/python3.5/site-packages/telegram/vendor/ptb_urllib3/urllib3/connection.py", line 284, in connect
    conn = self._new_conn()
  File "/home/hexor/.local/lib/python3.5/site-packages/telegram/vendor/ptb_urllib3/urllib3/connection.py", line 146, in _new_conn
    (self.host, self.timeout))
telegram.vendor.ptb_urllib3.urllib3.exceptions.ConnectTimeoutError: (<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7fba18c11630>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hexor/.local/lib/python3.5/site-packages/telegram/utils/request.py", line 189, in _request_wrapper
    resp = self._con_pool.request(*args, **kwargs)
  File "/home/hexor/.local/lib/python3.5/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 66, in request
    **urlopen_kw)
  File "/home/hexor/.local/lib/python3.5/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 87, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/home/hexor/.local/lib/python3.5/site-packages/telegram/vendor/ptb_urllib3/urllib3/poolmanager.py", line 244, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/hexor/.local/lib/python3.5/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 695, in urlopen
    **response_kw)
  File "/home/hexor/.local/lib/python3.5/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 695, in urlopen
    **response_kw)
  File "/home/hexor/.local/lib/python3.5/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 695, in urlopen
    **response_kw)
  File "/home/hexor/.local/lib/python3.5/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 666, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/hexor/.local/lib/python3.5/site-packages/telegram/vendor/ptb_urllib3/urllib3/util/retry.py", line 376, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
telegram.vendor.ptb_urllib3.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot409823338:AAGQfD0X_Je2ppudyDy07uqlslL01KPUBKg/getMe (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7fba18c11630>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 132, in <module>
    init()
  File "main.py", line 88, in init
    q, mutex, slaves)
  File "/home/hexor/Apps/ehForwarderBot/plugins/eh_telegram_master/__init__.py", line 122, in __init__
    self.me = self.bot.bot.get_me()
  File "/home/hexor/.local/lib/python3.5/site-packages/telegram/bot.py", line 57, in decorator
    result = func(self, *args, **kwargs)
  File "/home/hexor/.local/lib/python3.5/site-packages/telegram/bot.py", line 191, in get_me
    result = self._request.get(url, timeout=timeout)
  File "/home/hexor/.local/lib/python3.5/site-packages/telegram/utils/request.py", line 239, in get
    result = self._request_wrapper('GET', url, **urlopen_kwargs)
  File "/home/hexor/.local/lib/python3.5/site-packages/telegram/utils/request.py", line 195, in _request_wrapper
    raise NetworkError('urllib3 HTTPError {0}'.format(error))
telegram.error.NetworkError: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot409823338:AAGQfD0X_Je2ppudyDy07uqlslL01KPUBKg/getMe (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7fba18c11630>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))

**Comment by Hexor** [comment]
已经解决 自己加了代理后解决.
 export HTTP_PROXY=xxx
 export HTTPS_PROXY=xxx
