### ISSUE TITLE
pysqlite or sqlite3 must be installed

### ISSUE THREAD

**Issue by skyfore** [blueset/ehForwarderBot#84]
连接上了但是没有反应
控制台提示
```
Traceback (most recent call last):
  File "main.py", line 132, in <module>
    init()
  File "main.py", line 87, in init
    master = getattr(__import__(config.master_channel[0], fromlist=config.master_channel[1]), config.master_channel[1])(
  File "/home/ytt/files/ehForwarderBot/plugins/eh_telegram_master/__init__.py", line 21, in <module>
    from . import db, speech
  File "/home/ytt/files/ehForwarderBot/plugins/eh_telegram_master/db.py", line 304, in <module>
    db.connect()
  File "/usr/local/lib/python3.5/site-packages/peewee.py", line 3680, in connect
    self._local.conn = self._create_connection()
  File "/usr/local/lib/python3.5/site-packages/peewee.py", line 3708, in _create_connection
    return self._connect(self.database, **self.connect_kwargs)
  File "/usr/local/lib/python3.5/site-packages/peewee.py", line 3960, in _connect
    raise ImproperlyConfigured('pysqlite or sqlite3 must be installed.')
peewee.ImproperlyConfigured: pysqlite or sqlite3 must be installed.
```

**Comment by longkeyy** [comment]
pysqlite or sqlite3 must be installed.
pip install sqlite3
全国妖防组
QQ:  27779810
mail: chenyi@solr.cc



在 2017年9月20日，12:05，skyfore <notifications@github.com> 写道：

连接上了但是没有反应
控制台提示

Traceback (most recent call last):
  File "main.py", line 132, in <module>
    init()
  File "main.py", line 87, in init
    master = getattr(__import__(config.master_channel[0], fromlist=config.master_channel[1]), config.master_channel[1])(
  File "/home/ytt/files/ehForwarderBot/plugins/eh_telegram_master/__init__.py", line 21, in <module>
    from . import db, speech
  File "/home/ytt/files/ehForwarderBot/plugins/eh_telegram_master/db.py", line 304, in <module>
    db.connect()
  File "/usr/local/lib/python3.5/site-packages/peewee.py", line 3680, in connect
    self._local.conn = self._create_connection()
  File "/usr/local/lib/python3.5/site-packages/peewee.py", line 3708, in _create_connection
    return self._connect(self.database, **self.connect_kwargs)
  File "/usr/local/lib/python3.5/site-packages/peewee.py", line 3960, in _connect
    raise ImproperlyConfigured('pysqlite or sqlite3 must be installed.')
peewee.ImproperlyConfigured: pysqlite or sqlite3 must be installed.

**Comment by skyfore** [comment]
我已经安装了sqlite3 
```bash
#sqlite3 --version

3.20.1 2017-08-24 16:21:36 8d3a7ea6c5690d6b7c3767558f4f01b511c55463e3f9e64506801fe9b74dce34
```

> 虽然我是通过apt装的，因为pip提示无法下载

**Comment by skyfore** [comment]
@longkeyy

**Comment by blueset** [comment]
http://lmgtfy.com/?q=python3+sqlite3+install+%3Cyour_distro%3E
