### ISSUE TITLE
扫码登录微信确认后直接报下面的错误log，可以分析出是什么原因么

### ISSUE THREAD

**Issue by xudbin** [blueset/ehForwarderBot#87]
2017-09-26 23:18:46,297: plugins.eh_wechat_slave.WeChatChannel [CRITICAL]
    Tap "Confirm" to continue.
Traceback (most recent call last):
  File "main.py", line 132, in <module>
    init()
  File "main.py", line 84, in init
    slaves[obj.channel_id] = obj(q, mutex)
  File "/usr/local/ehForwarderBot/plugins/eh_wechat_slave.py", line 127, in __init__
    qrCallback=self.console_qr_code)
  File "/usr/lib/python3.6/site-packages/itchat/components/register.py", line 32, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "/usr/lib/python3.6/site-packages/itchat/components/login.py", line 53, in login
    status = self.check_login()
  File "/usr/lib/python3.6/site-packages/itchat/components/login.py", line 137, in check_login
    if process_login_info(self, r.text):
  File "/usr/lib/python3.6/site-packages/itchat/components/login.py", line 172, in process_login_info
    for node in xml.dom.minidom.parseString(r.text).documentElement.childNodes:
  File "/usr/lib64/python3.6/xml/dom/minidom.py", line 1968, in parseString
    return expatbuilder.parseString(string)
  File "/usr/lib64/python3.6/xml/dom/expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
  File "/usr/lib64/python3.6/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: no element found: line 1, column 0

**Comment by gaomx** [comment]
今天我这边也报了同样的错

**Comment by coffeecaty** [comment]
网页版微信被ban了 thanks by jqqqqqqq（不知道几个q）

**Comment by blueset** [comment]
多半是被 ban 了。参见 [Wiki](https://github.com/blueset/ehForwarderBot/wiki/EWS:-Current-reports-regarding-potential-actions-that-triggers-Web-WeChat-ban)。
