### ISSUE TITLE
OSError: cannot identify image file 

### ISSUE THREAD

**Issue by liwanglin12** [blueset/ehForwarderBot#90]
2017-10-19 01:06:32,062: telegram.ext.dispatcher [ERROR]
    An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/telegram/ext/dispatcher.py", line 270, in process_update
    handler.handle_update(update, self)
  File "/home/pi/.local/lib/python3.5/site-packages/telegram/ext/messagehandler.py", line 169, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/home/pi/ehForwarderBot/plugins/eh_telegram_master/__init__.py", line 1128, in msg
    return self.process_telegram_message(bot, update)
  File "/home/pi/ehForwarderBot/plugins/eh_telegram_master/__init__.py", line 1340, in process_telegram_message
    slave_msg = self.slaves[channel].send_message(m)
  File "/home/pi/ehForwarderBot/plugins/eh_wechat_slave.py", line 668, in send_message
    img = Image.open(msg.path)
  File "/home/pi/.local/lib/python3.5/site-packages/PIL/Image.py", line 2572, in open
    % (filename if filename else fp))
OSError: cannot identify image file 'storage/eh_telegram_master/Sticker_-210908714_11727_1508346391.webp'

**Comment by RoyXiang** [comment]
Please make sure `libwebp` is installed before the installation of `Pillow`.

References:
https://ehforwarderbot.readthedocs.io/en/latest/installation/#non-python-dependencies 
http://pillow.readthedocs.io/en/latest/installation.html#external-libraries

**Comment by liwanglin12** [comment]
Remove PIL & pillow in site-packages and re-install with libwebp, fixed.
